### ISSUE TITLE
Shows with numbers in their name wont show up anywhere

### ISSUE THREAD

**Issue by pablo3x6** [cglatot/pasta#49]
**Describe the bug**

**To Reproduce**
1. Go to any series
2. Click on any letter
3. Scroll down to anywhere
4. You cant see the shows that start their name with numbers. For example, you cant find 'The 100'

**Expected behavior**
Some way to find shows that don't start with letters beside the season search

**Comment by Animorphs** [comment]
This isn't a bug, these shows are under the "#" letter, which is before "A". 
Currently the "#" view is bugged however (due to Plex, not PASTA), so you might have to scroll a bit until you find the show you're looking for.

**Comment by pablo3x6** [comment]
> This isn't a bug, these shows are under the "#" letter, which is before "A". Currently the "#" view is bugged however (due to Plex, not PASTA), so you might have to scroll a bit until you find the show you're looking for.

MIght I ask if it's possible to make it so I could see which show is which?
Here is an image of [what I see](https://i.imgur.com/CsJ6GLI.png) when i click on #.

**Comment by Animorphs** [comment]
Yep I currently see the same thing, because of the aforementioned Plex bug, also mentioned in #40. If it says "Season X", "Special", etc. it's just a bug and you can scroll past it. This will be fixed by Plex in a month or so.
If you scroll far enough on the # tab, you will get to the actual numbered shows, [as seen on mine when I scroll down a bit](https://i.imgur.com/lDfOahR.png).

**Comment by pablo3x6** [comment]
You were right, I'm sorry, I just had so much to scroll I would've never found it looking as I have. No clue why I didn't just CTRL-F the whole thing.
