### ISSUE TITLE
Incorrect episode sort order for "Entire series" selection

### ISSUE THREAD

**Issue by SnoFox** [cglatot/pasta#51]
**Describe the bug**
When setting the audio/subtitles for an entire season, the modal displays the episodes changed out of order

**To Reproduce**
1. Select "Entire series" on something with multiple seasons
2. Set audio/subs

**Expected behavior**
Output would be in season/episode sort order for easily spotting episodes that didn't get changed

**Screenshots**
![vlcsnap-2022-03-02-19h57m24s462](https://user-images.githubusercontent.com/37625/156493566-f5f2ea60-b32c-4a74-80af-5b880c4abb4f.png)
![vlcsnap-2022-03-02-19h57m32s906](https://user-images.githubusercontent.com/37625/156493587-f9ae9e0f-5756-4e73-89c7-1d950c393cff.png)

Or a lot of screenshots at 30fps:
https://user-images.githubusercontent.com/37625/156493810-336d7e15-f687-4a59-af23-e1a10c50091f.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro build 19044.1526
 - Browser: Mozilla Firefox
 - Version: 97.0.1 (64-bit)

**Comment by cglatot** [comment]
This isn't a bug, but a feature request. Since the processing is done entirely client side, I wrote it to work as quickly as possible. That means asynchronous processing of the updates, and I have no control over which ones will be completed first. When a track is completed, it's added to the list, and the progress bar is updated.

If I were to try to sort these in order I would need to either make it a synchronous process, or some sort of post-processing where I manipulate the UI and sort the list based on the S?E? nomenclature. Both of these will add additional time to the processing, which is something I want to avoid.

I will see if I can do something about this that doesn't add a lot of time, but it is going to be a very low priority - there are other areas I want to focus my time first.

**Comment by SnoFox** [comment]
What is the intended purpose behind the log output after the progress bar? I intended to use it to spot problems in execution. In its current form, it is difficult to use for this purpose as it acts as a simple log file of changes. For example, in my current library, Attack on Titan Season 4 has 28 episodes, but only 16 of them are dual audio. Selecting "Entire Series" and picking an English track tells currently just tells you "everything succeeded" and it is non-obvious that half the season did not do as intended.

A couple of alternatives:
1. Only display non-matched and non-perfectly matched episodes
2. Assign a color to each of the match confidences (full match, no match, name only, code only) and paint the `span`/some word that color

Both of these would help to see if, at a glance, something went wrong during execution without jeopardizing async calls or creating post-processing time.

**Comment by cglatot** [comment]
Fixed in #69
