### ISSUE TITLE
Libraries not loading

### ISSUE THREAD

**Issue by TubbinSauce** [cglatot/pasta#71]
Hello! I've tried a couple different ways, I can continually get my server to show up, but clicking on the server the libraries never load. I used pasta before multiple times, not sure why it's not functional for me now : (

**Comment by cglatot** [comment]
Have you tried using the "Connect using local IP address"? That works most consistently.

Logging in via Plex account, and connecting without the local IP address can take a long time for the libraries to show up (for me it takes at least 30 seconds or so, others aren't getting it back at all). I'm not sure what's causing this, but I haven't found a fix for it yet.

Another workaround that has worked for others is to use the Plex X Token instead of the login.
